### PR TITLE
Fixed header in DA

### LINKED ISSUE #23: header not working properly in desktop and mobile as well
Image

### PR DESCRIPTION
**Pull request by rusmeenkhan1**
Fix #23 

Test URLs:
- Before:  https://main--sling--da-pilot.aem.live/
- After: https://23-headerfix--sling--da-pilot.aem.page/

### CODE REVIEW

File: aemedge/blocks/header/header.js [hunk 1]
```diff
@@ -171,16 +171,16 @@ export default async function decorate(block) {
   if (navSections) {
     navSections.querySelectorAll(':scope .default-content-wrapper > ul > li').forEach((navSection) => {
       const navheading = Array.from(navSection.childNodes)
-        .find((node) => node.nodeType === Node.TEXT_NODE);
+        .find((node) => node.nodeName === 'P');
```
Comment (RitwikSrivastava) [inline aemedge/blocks/header/header.js:174]: Whats this change 'P' ?

**Comment by RitwikSrivastava** [comment]
Also, noticed one thing, the expanded header should close if clicked somewhere outside it. Currently its not happening.

**Review by kmurugulla — APPROVED** [review]
